server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost/alpaqa?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
backpack:
  details:
    backpackNameSequence: 1
    sequenceStep: 1